blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://docs.polpo.sh
    about: Check the docs before opening an issue
  - name: Discord
    url: https://discord.gg/xha8trjq
    about: Ask questions and share ideas
